### ISSUE TITLE
AttributeError: 'staticmethod' object has no attribute '__name__'

### ISSUE THREAD

**Issue by peterlee909** [shijieS/DMMN#6]
Hi,
I got an error when I tried to test the UA-DETRAC with the command:
python test_tracker_ua.py

The error message is as below:

Traceback (most recent call last):
  File "test_tracker_ua.py", line 12, in <module>
    from layers.dmmn.tracker import Tracker, Config
  File "/root/data/AIModel/DMMN/layers/dmmn/tracker.py", line 199, in <module>
    class TrackSet:
  File "/root/data/AIModel/DMMN/layers/dmmn/tracker.py", line 215, in TrackSet
    @staticmethod
  File "/root/data/anaconda3/envs/py36/lib/python3.6/site-packages/deco/conc.py", line 44, in __init__
    self.__name__ = f.__name__
AttributeError: 'staticmethod' object has no attribute '__name__'

Did I do anything wrong?
How could I fix it?
Thanks!

**Comment by ShivaniSwadi** [comment]
hi @shijieS even i m facing the same problem . how to fix this error
